version: '3.8'

services:
  piritos:
    build:
      context: .
      dockerfile: Dockerfile
    image: piritos:latest
    container_name: piritos
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - piritos-network

networks:
  piritos-network:
    driver: bridge
